export const FETCH_ABSENCES = "FETCH_ABSENCES";
export const FETCH_ABSENCES_SERVER_ERROR = "FETCH_ABSENCES_SERVER_ERROR";
export const FETCH_ABSENCES_SUCCESS = "FETCH_ABSENCES_SUCCESS";
export const FETCH_MEMBERS = "FETCH_MEMBERS";
export const FETCH_MEMBERS_SERVER_ERROR = "FETCH_MEMBERS_SERVER_ERROR";
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS";
export const SERVER_ERROR = "SERVER_ERROR";
export const NO_SERVER_ERROR = "NO_SERVER_ERROR";